name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        id: cypress
        uses: cypress-io/github-action@v6
        with:
          command: npx cypress run
        continue-on-error: true

      

      - name: Upload Mochawesome reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-reports
          path: cypress/results/mochawesome-report
