name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        id: cypress
        uses: cypress-io/github-action@v6
        with:
          command: npx cypress run --reporter mochawesome --reporter-options reportDir="cypress/results",overwrite=false,html=false,json=true
        continue-on-error: true

      - name: Merge Mochawesome JSON reports
        if: always()
        run: npx mochawesome-merge "cypress/results/*.json" > mochawesome.json

      - name: Generate HTML report from merged JSON
        if: always()
        run: npx marge mochawesome.json --reportDir=cypress/results --reportFilename=mochawesome-report

      - name: Upload Mochawesome reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-reports
          path: |
            mochawesome.json
            cypress/results/mochawesome-report.html
