name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    #how many jobs to run in parallel
    #if we use containers we need cypress dashboard to know
    #which jobs run where.
    strategy:
      matrix:
        containers: [1,2,3,4,5]
        
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        id: cypress
        uses: cypress-io/github-action@v6
        with:
          spec: cypress/e2e/first.cy.js
        continue-on-error: true

      

      - name: Upload Mochawesome reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-reports
          path: cypress/results/mochawesome-report
          retention-days: 10
